### ISSUE TITLE
Hey so sorry but this is about Raven Storm - you disabled posting to that bug report

### ISSUE THREAD

**Issue by hazeyez** [Taguar258/injectra#8]
When trying to set "server" after entering host,port,password & hitting "run" -- I get this message (below) -- any way you could post an update on the Raven Storm page? Or message me somehow? You could tag me like --> @Taguar258  Love the software, trying to use it!! **I am really sorry that i had to post this here, and not on the Raven Storm page!!!!**

Server> run                                                                                   
 * Serving Flask app "Raven-Storm-Server" (lazy loading)                                      
 * Environment: production                                                                    
   WARNING: This is a development server. Do not use it in a production deployment.           
   Use a production WSGI server instead.                                                      
 * Debug mode: off                                                                            
Traceback (most recent call last):                                                            
  File "/usr/share/Raven-Storm/CLIF_Framework/framework.py", line 109, in run                 
    command[1](console_command)                                                               
TypeError: server() takes 0 positional arguments but 1 was given                              
                                                                                              
During handling of the above exception, another exception occurred:                           
                                                                                              
Traceback (most recent call last):                                                            
  File "/usr/share/Raven-Storm/CLIF_Framework/framework.py", line 109, in run                 
    command[1](console_command)                                                               
TypeError: run() takes 0 positional arguments but 1 was given                                 
                                                                                              
During handling of the above exception, another exception occurred:                           
                                                                                              
Traceback (most recent call last):                                                            
  File "/usr/bin/rst", line 26, in <module>                                                   
    run()                                                                                     
  File "/usr/bin/rst", line 22, in run                                                        
    main_console.run()                                                                        
  File "/usr/share/Raven-Storm/CLIF_Framework/framework.py", line 111, in run                 
    command[1]()                                                                              
  File "/usr/share/Raven-Storm/modules/main.py", line 262, in server                          
    var.modules["Server"].run()                                                               
  File "/usr/share/Raven-Storm/CLIF_Framework/framework.py", line 111, in run                 
    command[1]()                                                                              
  File "/usr/share/Raven-Storm/modules/server/main.py", line 244, in run                      
    app.run(host=var.host, port=var.port, use_reloader=False)                                 
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 990, in run                
    run_simple(host, port, self, **options)                                                   
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 1010, in run_simple 
    inner()                                                                                   
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 950, in inner       
    srv = make_server(                                                                        
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 782, in make_server 
    return ThreadedWSGIServer(                                                                
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 688, in __init__    
    super().__init__(server_address, handler)  # type: ignore                                 
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__                            
    self.server_bind()                                                                        
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind                          
    socketserver.TCPServer.server_bind(self)                                                  
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind                         
    self.socket.bind(self.server_address)                                                     
OSError: [Errno 99] Cannot assign requested address

**Comment by Taguar258** [comment]
Hey @hazeyez, sorry for the late reply. I have been quite busy those last few weeks. Could you maybe send me the details you entered, specifically the host? The server module adds capabilities for creating a DIY botnet, making it possible for multiple instances to be connected to a central host, therefore increasing the theoretical power. The host value is not to be confused with the target IP. For your info, the project is sadly dead to me and I don't plan on continuing nor maintaining it. I count it as one of my first projects, and looking back at it makes me feel embarrassed.

**Comment by hazeyez** [comment]
@Taguar258 I figured out how to set the server host, so issue resolved. It also throws errors if you do not set a password.  The largest issue is just figuring out how to use the program due to poor documentation, but it's all good. I'm sorry to hear that you gave up on it. Onto bigger and better things! Good luck!

**Comment by Taguar258** [comment]
Glad you could resolve the issue. I am sorry to hear and am aware that the documentation of Raven-Storm is not good. I am working on many cool projects for which I just need to find the last bit of time to finally finish. Have a good one and thanks, I appreciate the motivation. Cheers

**Comment by justlikeit4** [comment]
how can i enable debug mode
